apiVersion: apps/v1
kind: Deployment
metadata:
  name: asu-course-tracker-api
  namespace: asu-course-tracker
  labels:
    app: asu-course-tracker-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asu-course-tracker-api
  template:
    metadata:
      labels:
        app: asu-course-tracker-api
    spec:
      containers:
      - name: api
        image: asu-course-tracker-api:latest  # Replace with your actual image
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_USER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: JWT_SECRET_KEY
        - name: JWT_ISSUER
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: JWT_ISSUER
        - name: JWT_AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: JWT_AUDIENCE
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: asu-course-tracker-api-service
  namespace: asu-course-tracker
spec:
  selector:
    app: asu-course-tracker-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

