# Production secrets template for GitHub Actions
# This file uses environment variable substitution with envsubst
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: asu-course-tracker
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  ECR_IMAGE: "${ECR_IMAGE}"

---
# Secret for database admin operations (migrations)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin-secrets
  namespace: asu-course-tracker
type: Opaque
stringData:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"